### PR TITLE
sbt 1.0 build

### PR DESCRIPTION
**Pull request by BrandonArp**
Addresses #17 

Main problem is that I can't see a way to cross compile with sbt 0.13.x due to the change in ForkOptions and moving the Tuple functions.

Also, I haven't touched the version since I didn't know what you would want to do there.

### CODE REVIEW

**Comment by josephearl** [comment]
Thanks for this @BrandonArp. I'm not particular bothered about cross-compiling for 0.13.x -- I'll update the README to note the last compatible version for 0.13.x.

**Comment by josephearl** [comment]
Will look into the CI failures.

**Comment by BrandonArp** [comment]
One of the CI failures was a mismatched version of scalatest.  I've fixed that as well as a problem with the scala version.  The AppVeyor build looks like a Java 7 problem.  I'm not familiar with how to do the AppVeyor builds.  One thing that has helped in my open source projects has been the use of a jdk wrapper script that @vjkoskela has put together here: https://github.com/KoskiLabs/jdk-wrapper.  From what I can tell, a good chunk of the AppVeyor build is installing a jdk. The wrapper script could potentially ease that.

**Comment by josephearl** [comment]
I've merged this into master, updated the appveyor script and released as 2.5.0 - let me know if you find any issues.

Will look into the wrapper script, thanks.

**Pull request closed without merging**
